name: Container Build
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/buildah-build-devel.yml # Self-trigger
      - containers/labs344/**

env:
  REGISTRY: ghcr.io/bouncmpe
  IMAGE_NAME: labs344
  LABS344_VERSION: latest
  CONTAINERS_ROOT: /home/runner/.local/share/containers
  TMPDIR: /home/runner/.local/share/containers/tmp

permissions:
  contents: read
  packages: write

jobs:
  buildah-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
      
    steps:
      - name: Install container tools
        run: sudo apt-get install podman buildah jq

      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 2048 # Reserve disk space for repository
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          build-mount-path: ${{ env.CONTAINERS_ROOT }} # The remaining space only for container build

      - run: mkdir -p $TMPDIR

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment variables
        run: |
          echo "HOSTARCH=$(podman info --format='{{.Host.Arch}}')" >> $GITHUB_ENV
          echo "PLATFORM=$(podman info --format='{{.Version.OsArch}}' | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "LABS344_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build builder container image
        id: build-builder
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.LABS344_VERSION }}-builder
            ${{ env.LABS344_VERSION }}-builder-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            LABS344_VERSION=${{ env.LABS344_VERSION }}
          extra-args: |
            --target labs344-builder
          containerfiles: |
            containers/labs344/Dockerfile
          context: containers

      - name: Build devel container image
        id: build-devel
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.LABS344_VERSION }}-devel
            ${{ env.LABS344_VERSION }}-devel-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            LABS344_VERSION=${{ env.LABS344_VERSION }}
          extra-args: |
            --target labs344-devel
          containerfiles: |
            containers/labs344/Dockerfile
          context: containers

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-builder-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-builder.outputs.image }}
          tags: ${{ env.LABS344_VERSION }}-builder-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-labs344-builder-${{ env.LABS344_VERSION }}-${{ env.PLATFORM }}

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-devel-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-devel.outputs.image }}
          tags: ${{ env.LABS344_VERSION }}-devel-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-labs344-devel-${{ env.LABS344_VERSION }}-${{ env.PLATFORM }}

      - name: Upload digests
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: digest-bouncmpe-${{ env.LABS344_VERSION }}-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digest-*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0 # no compression

  buildah-merge:
    name: Merge container images
    runs-on: ubuntu-24.04
    needs: buildah-build
    if: github.ref == 'refs/heads/main' && always()
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: Prepare environment variables
        run: |
          echo "LABS344_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest list for labs344-builder
        run: |
          MANIFEST=labs344-builder
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-labs344-builder-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.LABS344_VERSION }}-builder
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-builder

      - name: Create and push manifest list for labs344-devel
        run: |
          MANIFEST=labs344-devel
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-labs344-devel-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.LABS344_VERSION }}-devel
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-devel
