name: Build and push whisper image

on:
  push:
    paths:
      - docker/whisper.dockerfile
      - .github/workflows/build-and-push-whisper.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bouncmpe/whisper

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/whisper.dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cache-to: type=inline