name: Build and push whisper image

on:
  push:
    paths:
      - docker/whisper.dockerfile
      - .github/workflows/build-and-push-whisper.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bouncmpe/whisper

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - targetarch: amd64
            platform: amd64
          - targetarch: arm64v8
            platform: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/whisper.dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.targetarch }}
          build-args: |
            TARGETARCH=${{ matrix.targetarch }}
          platforms: linux/${{ matrix.platform }}
          push: false
          # cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.targetarch }}
          # cache-to: type=inline
