name: labs344-build

on:
  workflow_dispatch:
  push:
    paths:
      - containers/labs344/**
      - .github/workflows/labs344-build.yml # Self-trigger

env:
  REGISTRY: ghcr.io/bouncmpe
  IMAGE_NAME: labs344
  IMAGE_TAG: 2025-2026-1

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: containers/labs344
          provenance: mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
